query VrfIntent($device_name: String!) {
  InfraVRFDeviceAssignment(device__name__value: $device_name) {
    edges {
      node {
        route_distinguisher { value }
        vrf {
          node {
            name { value }
            description { value }
            route_distinguisher { value }
            l3vni {
              node {
                vni { value }
                vni_type { value }
              }
            }
            import_targets {
              edges {
                node {
                  target { value }
                }
              }
            }
            export_targets {
              edges {
                node {
                  target { value }
                }
              }
            }
          }
        }
        import_targets {
          edges {
            node {
              target { value }
            }
          }
        }
        export_targets {
          edges {
            node {
              target { value }
            }
          }
        }
      }
    }
  }
}
