query VxlanIntent($device_name: String!) {
  # VTEP configuration for the device
  InfraVTEP(device__name__value: $device_name) {
    edges {
      node {
        source_address {
          value
        }
        udp_port {
          value
        }
        learn_restrict {
          value
        }
        source_interface {
          node {
            name {
              value
            }
          }
        }
        # VLAN-to-VNI mappings (L2 VXLAN)
        vlan_vni_mappings {
          edges {
            node {
              description {
                value
              }
              vlan {
                node {
                  vlan_id {
                    value
                  }
                  name {
                    value
                  }
                }
              }
              vni {
                node {
                  vni {
                    value
                  }
                  vni_type {
                    value
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  # VRF-to-VNI mappings (L3 VXLAN) via VRF device assignments
  InfraVRFDeviceAssignment(device__name__value: $device_name) {
    edges {
      node {
        route_distinguisher {
          value
        }
        vrf {
          node {
            name {
              value
            }
            l3vni {
              node {
                vni {
                  value
                }
                vni_type {
                  value
                }
              }
            }
            import_targets {
              edges {
                node {
                  target {
                    value
                  }
                }
              }
            }
            export_targets {
              edges {
                node {
                  target {
                    value
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
